/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103x6.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void clock_init()
{
	// Enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	// Enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;
	// PA1 high Z Floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);
	// ---------------------------------*******************************------------------------
	//PB1:(output PUSH pull mode)
	//01: Output mode, max speed 10MHZ.
	//CNF00: General Purpose output push-pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
	//-----------------------------------******************************--------------------------------
	// PA1 high Z Floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);
	//-----------------------------------******************************--------------------------------
	//PB13:(output PUSH pull mode)
	//01: Output mode, max speed 10MHZ.
	//CNF00: General Purpose output push-pull
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);
}
void my_wait(int x)
{
	unsigned int i, j;
	for(i = 0; i<x; i++)
	{
		for(j = 0; j<255; j++);
	}
}
int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		// PA1 connected to PUR
		// first I mask with bit1 then shift it right to compare with decimal
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) //press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);//single press

		}
		//PA13 connected external PDR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1) //Multi press
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		my_wait(1);
	}




}
